const host = "http://localhost:8080"

enum Paths { 
    REGISTER = host + '/register',
    LOGIN = host + '/login',
    AUTH = host + '/auth/',
    VIEW_ALL_HOTEL = host + "/view-hotel",
GET_LOCATIONS = host + '/get_locations',
    CREATE_HOTEL   = host + "/create-hotel",
    CREATE_HOTEL_PICTURE= host + "/create_hotel_picture",
	CREATE_HOTEL_FACILITY = host + "/create_hotel_facility",
    CREATE_AIRLINE=host +  "/create_airline",
    GET_ALL_AIRLINE       = host + "/view_airline",
    GET_ALL_AIRPORT       = host + "/get_airport" ,
    CREATE_FLIGHT         = host + "/create_flight",
    GET_ALL_FLIGHT        = host+"/view_flight",
    GET_HOTEL_DETAIL = host + "/view-hotel",
    CREATE_HOTEL_ROOM_TYPE = host + "/create_room_type",
    CREATE_FLIGHT_TRANSIT = host + "/create_transit",GET_FLIGHT_DETAIL= host + "/view-flight",
    DELETE_ROOM_TYPE = host + "/delete_room_type",
    GET_ALL_USER           = host + "/get_all_user",
    BAN_HANDLE_USER = host + "/ban_handle_user",
    CREATE_PROMO = host + "/create_promo",
    GET_ALL_PROMO = host + "/view_promo",
    DELETE_PROMO= host + "/delete_promo",

    VIEW_ALL_HOTELROOMTYPEFACILITY = host + "/view_hotelroomtypefacility",
    VIEW_HOTELROOMTYPEFACILITY_BY_ID = host + "/view_hotelroomtypefacility",
    UPDATE_HOTELROOMTYPEFACILITY = host + "/update_hotelroomtypefacility",
    DELETE_HOTELROOMTYPEFACILITY = host + "/delete_hotelroomtypefacility",
    CREATE_HOTELROOMTYPEFACILITY = host + "/create_hotelroomtypefacility",

    VIEW_ALL_FLIGHTSEAT = host + "/view_flightseat",
    VIEW_FLIGHTSEAT_BY_ID = host + "/view_flightseat",
    UPDATE_FLIGHTSEAT = host + "/update_flightseat",
    DELETE_FLIGHTSEAT = host + "/delete_flightseat",
    CREATE_FLIGHTSEAT = host + "/create_flightseat",
    TEST =  host + "/create_flightseatasdfadsf",

    VIEW_ALL_CARTFLIGHTTICKET = host + "/view_cartflightticket",
    VIEW_CARTFLIGHTTICKET_BY_ID = host + "/view_cartflightticket",
    UPDATE_CARTFLIGHTTICKET = host + "/update_cartflightticket",
    DELETE_CARTFLIGHTTICKET = host + "/delete_cartflightticket",
    CREATE_CARTFLIGHTTICKET = host + "/create_cartflightticket",

    VIEW_ALL_CARTHOTELTICKET = host + "/view_carthotelticket",
    VIEW_CARTHOTELTICKET_BY_ID = host + "/view_carthotelticket",
    UPDATE_CARTHOTELTICKET = host + "/update_carthotelticket",
    DELETE_CARTHOTELTICKET = host + "/delete_carthotelticket",
    CREATE_CARTHOTELTICKET = host + "/create_carthotelticket",

    GET_USER_DETAIL = host+ "/user",
    UPDATE_PASSWORD = host + "/user/update",

    VIEW_ALL_FLIGHTTICKET = host + "/view_flightticket",
    SEARCH_FLIGHTTCKET    = host + "/search_flightticket",
    VIEW_FLIGHTTICKET_BY_ID = host + "/view_flightticket",
    UPDATE_FLIGHTTICKET = host + "/update_flightticket",
    DELETE_FLIGHTTICKET = host + "/delete_flightticket",
    CREATE_FLIGHTTICKET = host + "/create_flightticket",
    BUY_FLIGHT              = host + "/buy_flight",

    VIEW_ALL_HOTELTICKET = host + "/view_hotelticket",
	SEARCH_HOTELTICKET   = host + "/search_hotelticket",
    UPDATE_HOTELTICKET = host + "/update_hotelticket",
    DELETE_HOTELTICKET = host + "/delete_hotelticket",
    CREATE_HOTELTICKET = host + "/create_hotelticket",
    BUY_HOTEL              = host + "/buy_hotel",
    LOGOUT = host + "/log_out",

    UPDATE_PROMO = host + "/update_promo",
    HOTEL_RECOMMENDATION = host + "/hotel_recommendation",
    FLIGHT_RECOMMENDATION = host + "/flight_recommendation",
    HISTORY_HOTEL_TICKET  = host + "/history_hotel_ticket",
	HISTORY_FLIGHT_TICKET = host + "/history_flight_ticket",
    VIEW_ALL_RATING = host + "/view_rating",
    VIEW_RATING_BY_ID = host + "/view_rating",
    UPDATE_RATING = host + "/update_rating",
    DELETE_RATING = host + "/delete_rating",
    CREATE_RATING = host + "/create_rating",

    VIEW_ALL_REVIEW = host + "/view_review",
    VIEW_REVIEW_BY_ID = host + "/view_review",
    UPDATE_REVIEW = host + "/update_review",
    DELETE_REVIEW = host + "/delete_review",
    CREATE_REVIEW = host + "/create_review",
    UPDATE_USER_INFORMATION = host + "/update_user_information",
    USER_SUBSCRIBE = host + "/user_subscribe",
    VIEW_ALL_CREDITCARD = host + "/view_creditcard",
    VIEW_CREDITCARD_BY_ID = host + "/view_creditcard",
    UPDATE_CREDITCARD = host + "/update_creditcard",
    DELETE_CREDITCARD = host + "/delete_creditcard",
    CREATE_CREDITCARD = host + "/create_creditcard",
    ADD_BALANCE = host + "/add_balance",

    FILTER_FLIGHTS = host + "/filter-flights",
    FILTER_HOTELS = host + "/filter-hotels",
    GET_OTP = host + "/get-otp",
	OTP_LOGIN = host + "/login-otp",
    SEARCH_RECOMMENDATION = host + "/search-recommendation",
    SEARCH_QUERY = host + "/search-query",
    SEARCH_FLIGHTS = host + "/filter-flights",
	SEARCH_HOTELS= host + "/filter-hotels",
    ADD_SEARCH_HISTORY = host + "/add-search-history",
    ADMIN_EMAIL = host + "/admin-email"
}


export default Paths
